//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotApp.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BotApp.Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt;.
        /// </summary>
        internal static string BoldFmt {
            get {
                return ResourceManager.GetString("BoldFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bot is running.
        /// </summary>
        internal static string BotStarted {
            get {
                return ResourceManager.GetString("BotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bot is stopped.
        /// </summary>
        internal static string BotStopped {
            get {
                return ResourceManager.GetString("BotStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation data for today..
        /// </summary>
        internal static string CalculationToday {
            get {
                return ResourceManager.GetString("CalculationToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation data for tomorrow..
        /// </summary>
        internal static string CalculationTomorrow {
            get {
                return ResourceManager.GetString("CalculationTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation data for yesterday..
        /// </summary>
        internal static string CalculationYesterday {
            get {
                return ResourceManager.GetString("CalculationYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day length: &lt;code&gt;{0}&lt;/code&gt;.
        /// </summary>
        internal static string DayLengthFmt {
            get {
                return ResourceManager.GetString("DayLengthFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of week: &lt;code&gt;{0}&lt;/code&gt; (Planet: &lt;code&gt;{1}&lt;/code&gt;).
        /// </summary>
        internal static string DayOfWeekFmt {
            get {
                return ResourceManager.GetString("DayOfWeekFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Exception:&lt;/b&gt; &lt;em&gt;{0}&lt;/em&gt;.
        /// </summary>
        internal static string ExceptionMessageFmt {
            get {
                return ResourceManager.GetString("ExceptionMessageFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First, send your coordinates..
        /// </summary>
        internal static string FirstSendYourCoordinates {
            get {
                return ResourceManager.GetString("FirstSendYourCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour length: &lt;code&gt;{0}&lt;/code&gt;.
        /// </summary>
        internal static string HourLengthFmt {
            get {
                return ResourceManager.GetString("HourLengthFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu menu.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:00} min..
        /// </summary>
        internal static string MinutesShort {
            get {
                return ResourceManager.GetString("MinutesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night length: &lt;code&gt;{0}&lt;/code&gt;.
        /// </summary>
        internal static string NightLengthFmt {
            get {
                return ResourceManager.GetString("NightLengthFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Now:&lt;/b&gt; &lt;code&gt;{0}&lt;/code&gt;.
        /// </summary>
        internal static string NowFmt {
            get {
                return ResourceManager.GetString("NowFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        internal static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send information about your location.
        /// </summary>
        internal static string PleaseSendLocation {
            get {
                return ResourceManager.GetString("PleaseSendLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the time zone.
        /// </summary>
        internal static string SelectTimezone {
            get {
                return ResourceManager.GetString("SelectTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send location.
        /// </summary>
        internal static string SendLocation {
            get {
                return ResourceManager.GetString("SendLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the Scheduler.
        /// </summary>
        internal static string StopScheduler {
            get {
                return ResourceManager.GetString("StopScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunrise: &lt;code&gt;{0}&lt;/code&gt;.
        /// </summary>
        internal static string SunriseFmt {
            get {
                return ResourceManager.GetString("SunriseFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunset: &lt;code&gt;{0}&lt;/code&gt;.
        /// </summary>
        internal static string SunsetFmt {
            get {
                return ResourceManager.GetString("SunsetFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. &lt;b&gt;{1}&lt;/b&gt; &lt;code&gt;{2}&lt;/code&gt; - &lt;code&gt;{3}&lt;/code&gt;.
        /// </summary>
        internal static string TableRowFmt {
            get {
                return ResourceManager.GetString("TableRowFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for sending information about your location..
        /// </summary>
        internal static string ThankSendLocation {
            get {
                return ResourceManager.GetString("ThankSendLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        internal static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong location.
        /// </summary>
        internal static string WrongLocation {
            get {
                return ResourceManager.GetString("WrongLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your location data has been received..
        /// </summary>
        internal static string YourLocationReceived {
            get {
                return ResourceManager.GetString("YourLocationReceived", resourceCulture);
            }
        }
    }
}
